### ISSUE TITLE
How to handle many slice files

### ISSUE THREAD

**Issue by fintfire** [zeroc-ice/ice-builder-msbuild#5]
In my netcore project，there were about 180 slice files. Because "All the Slice files in a given project are compiled through a single slice2cs invocation"，the command line length exceed the windows limit 8191. Then the slice2cs.exe keep running and i had to kill it manually. I guess the command line was cut improperly.
Is it possible invocation slice2cs for single slice?

**Comment by pepone** [comment]
Hi Flint,

If you run slice2cs manually or with a custom build step you can use "slice2cs *.ice ....", the builder doesn't use file patterns and adds each file that belong to the project with its name to the command line. ( I assume that pattern expansion helps overcome this limitation but didn't actually check)

As a workaround you can consider merge some of your Slice files.

https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

In this article Microsoft suggests to write the command line to a file that can be used as input for the program, Slice compilers doesn't support this but it is something we can consider adding in a future release.

**Comment by fintfire** [comment]
Thanks, pepone.
